import {
  getOfficialAbsenceMinutes,
  getTimedLeaveMinutes,
  isLongApprovedDeparture,
  isPolicyEffective,
  MAX_PARTIAL_ABSENCE_MINUTES
} from './attendancePolicy.js';

export const roundMinutes = (minutes, roundingMethod) => {
  if (!roundingMethod || roundingMethod === 'minute') return minutes;
  if (roundingMethod === '15_minutes') return Math.round(minutes / 15) * 15;
  if (roundingMethod === '30_minutes') return Math.round(minutes / 30) * 30;
  if (roundingMethod === 'hour') return Math.round(minutes / 60) * 60;
  return minutes;
};

export const getCycleDates = (monthStr, startDay) => {
  const [year, month] = monthStr.split('-').map(Number);
  const day = startDay || 1;

  if (day === 1) {
    const lastDay = new Date(year, month, 0).getDate();
    return {
      start: `${year}-${String(month).padStart(2, '0')}-01`,
      end: `${year}-${String(month).padStart(2, '0')}-${String(lastDay).padStart(2, '0')}`
    };
  } else {
    let prevM = month - 1; let prevY = year;
    if (prevM === 0) { prevM = 12; prevY -= 1; }
    let currentLastDay = day - 1; let currentM = month; let currentY = year;
    if (currentLastDay === 0) {
      currentM = prevM; currentY = prevY;
      currentLastDay = new Date(currentY, currentM, 0).getDate();
    }
    return {
      start: `${prevY}-${String(prevM).padStart(2, '0')}-${String(day).padStart(2, '0')}`,
      end: `${currentY}-${String(currentM).padStart(2, '0')}-${String(currentLastDay).padStart(2, '0')}`
    };
  }
};

export const calculateSalaries = ({
  employees,
  hrSettings,
  holidays,
  violations,
  bonuses,
  attendance,
  leaves,
  advances,
  selectedMonth
}) => {
  if (!selectedMonth) {
    const today = new Date();
    selectedMonth = `${today.getFullYear()}-${(today.getMonth() + 1).toString().padStart(2, '0')}`;
  }
  const cycle = getCycleDates(selectedMonth, hrSettings.salaryCycleStartDay || 1);

  return employees.map(emp => {
    const basic = Number(emp.basicSalary) || 0;

    const [yStr, mStr] = selectedMonth.split('-');
    const daysInMonth = new Date(parseInt(yStr, 10), parseInt(mStr, 10), 0).getDate();
    
    let workDays = hrSettings.workDaysPerMonth || daysInMonth;
    if (hrSettings.workDaysStrategy === 'actual' || !hrSettings.workDaysStrategy) {
       workDays = daysInMonth;
    } else if (hrSettings.workDaysStrategy === 'custom' && hrSettings.customWorkDays) {
      const mIndex = parseInt(mStr, 10) - 1;
      if (!isNaN(mIndex) && hrSettings.customWorkDays[mIndex]) {
        workDays = hrSettings.customWorkDays[mIndex];
      }
    }
    
    const dailyRate = basic / workDays;
    
    // Get applicable holidays for this month
    const empHolidays = (holidays || []).filter(hol => {
      if (hol.isActive === false) return false;
      if (hol.targetAudience !== 'all' && hol.targetAudience !== `dept_${emp.department}`) return false;
      return (hol.fromDate >= cycle.start && hol.toDate <= cycle.end) || (hol.fromDate <= cycle.end && hol.toDate >= cycle.start);
    });
    
    const isDateInHoliday = (dateStr) => {
      return empHolidays.find(hol => dateStr >= hol.fromDate && dateStr <= hol.toDate);
    };
    
    let empStandardWorkHours = hrSettings.standardWorkHours || 8;
    if (emp.shiftStart && emp.shiftEnd) {
      const [sh, sm] = emp.shiftStart.split(':').map(Number);
      const [eh, em] = emp.shiftEnd.split(':').map(Number);
      if (!isNaN(sh) && !isNaN(sm) && !isNaN(eh) && !isNaN(em)) {
        let mins = (eh * 60 + em) - (sh * 60 + sm);
        if (mins < 0) mins += 24 * 60; // handle overnight shifts
        empStandardWorkHours = mins / 60;
        if (empStandardWorkHours <= 0) empStandardWorkHours = hrSettings.standardWorkHours || 8; // fallback if invalid
      }
    }
    
    const hourlyRate = dailyRate / empStandardWorkHours;
    
    // 1. Manual Violations
    const empViolations = violations.filter(v => {
      const isEmpMatch = String(v.employeeId || '').trim() === String(emp.id || '').trim() || String(v.employeeName || '').trim() === String(emp.name || '').trim();
      if (!isEmpMatch || v.status === 'محذوف') return false;
      if (v.autoGeneratedFromDailyReport && v.status !== 'موافق') return false;
      if (v.processedInPeriod && v.processedInPeriod !== selectedMonth) return false;
      if (!v.processedInPeriod) return v.date >= cycle.start && v.date <= cycle.end;
      return true;
    });
    const manualDeductions = empViolations.reduce((sum, v) => sum + (Number(v.deductionAmount) || 0), 0);

    // 1.5 Bonuses
    const empBonuses = bonuses.filter(b => {
      const isEmpMatch = String(b.employeeId || '').trim() === String(emp.id || '').trim() || String(b.employeeName || '').trim() === String(emp.name || '').trim();
      if (!isEmpMatch || b.status === 'محذوف') return false;
      if (b.processedInPeriod && b.processedInPeriod !== selectedMonth) return false;
      if (!b.processedInPeriod) return b.date >= cycle.start && b.date <= cycle.end;
      return true;
    });
    const bonusAddition = empBonuses.reduce((sum, b) => sum + (Number(b.amount) || 0), 0);
    const bonusesList = empBonuses.map(b => ({ type: b.type, amount: Number(b.amount) || 0 }));

    // 2. Attendance (Lateness & Absences)
    const empAttendance = attendance.filter(a => {
      const isEmpMatch = String(a.employeeId || '').trim() === String(emp.id || '').trim() || String(a.employeeName || '').trim() === String(emp.name || '').trim();
      return isEmpMatch && a.date >= cycle.start && a.date <= cycle.end;
    });
    const rawLateMinutes = empAttendance.reduce((sum, a) => sum + (Number(a.lateMinutes) || 0), 0);
    
    const unpaidLeaveDates = new Set();
    empAttendance.forEach(a => {
      if (a.status === 'إجازة غير مدفوعة' && a.date) {
        unpaidLeaveDates.add(a.date);
      }
    });

    const unexcusedAbsenceDates = new Set();
    empAttendance.forEach(a => {
      if (a.status === 'غياب غير مبرر' && a.date) {
        unexcusedAbsenceDates.add(a.date);
      }
    });
    
    const approvedStatuses = ['موافق', 'موافق عليه', 'مقبول', 'تمت الموافقة', 'تم التسليم'];
    const empLeaves = leaves.filter(l => {
      const isApproved = approvedStatuses.includes(l.status);
      const isEmpMatch = String(l.employeeId || '').trim() === String(emp.id || '').trim() || String(l.employeeName || '').trim() === String(emp.name || '').trim();
      if (!isEmpMatch || !isApproved) return false;
      if (l.date) return l.date >= cycle.start && l.date <= cycle.end;
      if (l.startDate && l.endDate) return l.startDate <= cycle.end && l.endDate >= cycle.start;
      return false;
    });

    const automaticUnpaidDates = new Set();
    empAttendance.forEach(attendanceRow => {
      if (!isPolicyEffective(attendanceRow.date)) return;
      const officialAbsenceMinutes = getOfficialAbsenceMinutes({
        timeIn: attendanceRow.timeIn,
        timeOut: attendanceRow.timeOut,
        shiftStart: emp.shiftStart || '08:00',
        shiftEnd: emp.shiftEnd || '16:00'
      });
      if (officialAbsenceMinutes > MAX_PARTIAL_ABSENCE_MINUTES) {
        automaticUnpaidDates.add(attendanceRow.date);
      }
    });
    empLeaves.forEach(leave => {
      if (isLongApprovedDeparture(leave)) {
        automaticUnpaidDates.add(leave.date || leave.startDate);
      }
    });
    automaticUnpaidDates.forEach(date => unpaidLeaveDates.add(date));
    
    let missionMinutes = 0;
    
    empLeaves.forEach(leave => {
      if (leave.type === 'مغادرة خاصة' || leave.type === 'مغادرة عمل' || leave.type === 'مغادرة الدخان') {
        const leaveDate = leave.date || leave.startDate;
        if (automaticUnpaidDates.has(leaveDate)) return;
        if (leave.startTime && leave.endTime) {
          missionMinutes += getTimedLeaveMinutes(leave);
        }
      }
    });
    
    // Automatic Unexcused Absence Detection
    const todayObj = new Date();
    const yesterdayObj = new Date(todayObj);
    yesterdayObj.setDate(yesterdayObj.getDate() - 1);
    const yesterdayStr = `${yesterdayObj.getFullYear()}-${String(yesterdayObj.getMonth() + 1).padStart(2, '0')}-${String(yesterdayObj.getDate()).padStart(2, '0')}`;
    const endProcessDate = cycle.end > yesterdayStr ? yesterdayStr : cycle.end;
    
    const arabicDays = ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'];
    const weekends = hrSettings.weekendDays || ['الجمعة'];
    
    let currentDay = new Date(cycle.start);
    const lastDay = new Date(endProcessDate);
    const nonWorkStatuses = ['غائب', 'غياب غير مبرر', 'إجازة سنوية', 'إجازة مرضية', 'إجازة غير مدفوعة', 'لم يسجل دخول', 'محذوف'];
    let elapsedWorkDays = 0;

    while (currentDay <= lastDay) {
      const year = currentDay.getFullYear();
      const month = String(currentDay.getMonth() + 1).padStart(2, '0');
      const day = String(currentDay.getDate()).padStart(2, '0');
      const dateStr = `${year}-${month}-${day}`;
      const dayName = arabicDays[currentDay.getDay()];
      
      // Skip weekends
      if (weekends.includes(dayName)) {
        currentDay.setDate(currentDay.getDate() + 1);
        continue;
      }
      
      // Skip holidays
      if (isDateInHoliday(dateStr)) {
        currentDay.setDate(currentDay.getDate() + 1);
        continue;
      }
      
      elapsedWorkDays++;

      // Check if leave exists in HR leaves (Approved leaves take precedence over actual/mistaken attendance)
      const leaveForDay = empLeaves.find(l => (l.date && l.date === dateStr) || (l.startDate && l.startDate <= dateStr && l.endDate >= dateStr));
      if (leaveForDay) {
        if (String(leaveForDay.type || '').trim() === 'إجازة غير مدفوعة') {
          unpaidLeaveDates.add(dateStr);
        }
        currentDay.setDate(currentDay.getDate() + 1);
        continue;
      }

      // Skip if actual attendance exists (meaning they worked)
      const hasActualAttendance = empAttendance.some(a => 
        a.date === dateStr && 
        a.status && String(a.status).trim() !== '' &&
        !nonWorkStatuses.includes(a.status)
      );
      
      if (hasActualAttendance) {
        currentDay.setDate(currentDay.getDate() + 1);
        continue;
      }
      
      // Skip if attendance explicitly marks an excused leave
      const hasExcusedAbsenceInAttendance = empAttendance.some(a => 
        a.date === dateStr && 
        ['إجازة سنوية', 'إجازة مرضية', 'إجازة غير مدفوعة', 'إجازة', 'مغادرة'].includes(a.status)
      );
      if (hasExcusedAbsenceInAttendance) {
        currentDay.setDate(currentDay.getDate() + 1);
        continue;
      }
      
      // Unexcused absence
      unexcusedAbsenceDates.add(dateStr);
      currentDay.setDate(currentDay.getDate() + 1);
    }
    
    const unexcusedAbsenceDays = unexcusedAbsenceDates.size;
    const unpaidLeaveDays = unpaidLeaveDates.size;
    
    // Smart overtime approval can settle attendance deficit from the requested
    // period. Those minutes are neither payable overtime nor a second salary
    // deduction. Legacy smart approvals stored only compMins, so keep that as
    // a fallback for already-approved records.
    const coveredLateMinutesByDate = empLeaves
      .filter(l => l.type === 'بدل عمل إضافي' || l.type === 'عمل إضافي')
      .reduce((byDate, l) => {
        const details = l.rateDetails;
        if (!details) return byDate;
        const explicitLate = Number(details.lateCoveredMins);
        const legacyCovered = Number(details.compMins);
        const covered = Number.isFinite(explicitLate)
          ? Math.max(0, explicitLate)
          : (Number.isFinite(legacyCovered) ? Math.max(0, legacyCovered) : 0);
        const date = l.date || l.startDate;
        if (date) byDate.set(date, (byDate.get(date) || 0) + covered);
        return byDate;
      }, new Map());
    // Cap coverage against lateness on the same attendance day. This prevents
    // duplicate requests or early-departure coverage from cancelling lateness
    // belonging to another day.
    const payableLateMinutes = empAttendance.reduce((sum, attendanceRow) => {
      if (unpaidLeaveDates.has(attendanceRow.date)) return sum;
      const late = Math.max(0, Number(attendanceRow.lateMinutes) || 0);
      const covered = coveredLateMinutesByDate.get(attendanceRow.date) || 0;
      return sum + Math.max(0, late - covered);
    }, 0);
    const coveredLateMinutes = Math.max(0, rawLateMinutes - payableLateMinutes);
    const roundedLateMinutes = roundMinutes(payableLateMinutes, hrSettings.timeRounding);
    const roundedMissionMinutes = roundMinutes(missionMinutes, hrSettings.timeRounding);
    
    let lateDeduction = 0;
    let unpaidLeaveDeduction = 0;
    
    // Lateness & Missions Handling
    if (hrSettings.latenessHandling === 'deduct_from_balance' || !hrSettings.latenessHandling) {
      const totalMinutesToDeduct = roundedLateMinutes + roundedMissionMinutes;
      const balance = hrSettings.monthlyMissionBalanceMinutes || 120;
      if (totalMinutesToDeduct > balance) {
        const overBalanceMins = totalMinutesToDeduct - balance;
        lateDeduction = (overBalanceMins / 60) * hourlyRate;
      }
    } else if (hrSettings.latenessHandling === 'financial_deduction') {
      lateDeduction = ((roundedLateMinutes + roundedMissionMinutes) / 60) * hourlyRate;
    } // If warning_only, deduction is 0
    
    let unexcusedAbsenceDeduction = 0;
    
    // Absence Handling
    // Unpaid Leave Deduction (Unconditionally deducted since it's an approved unpaid request)
    if (hrSettings.absenceHandling === 'work_hours') {
      unpaidLeaveDeduction = unpaidLeaveDays * (empStandardWorkHours * hourlyRate);
    } else {
      unpaidLeaveDeduction = unpaidLeaveDays * dailyRate;
    }

    // Unexcused Absence Deduction (Depends on absenceHandling strategy)
    if (hrSettings.absenceHandling === 'full_day' || (!hrSettings.absenceHandling && hrSettings.fullDayAbsenceDeduction)) {
      unexcusedAbsenceDeduction = unexcusedAbsenceDays * dailyRate;
    } else if (hrSettings.absenceHandling === 'work_hours') {
      unexcusedAbsenceDeduction = unexcusedAbsenceDays * (empStandardWorkHours * hourlyRate);
    } else {
      unexcusedAbsenceDeduction = 0; // needs_approval means 0 automatic deduction for unexcused absence
    }
    
    // 2.5 Approved Overtime Requests
    const overtimeReqs = leaves.filter(l => {
      const isApproved = approvedStatuses.includes(l.status);
      if (l.employeeId !== emp.id || (l.type !== 'بدل عمل إضافي' && l.type !== 'عمل إضافي') || !isApproved) return false;
      const overtimeDate = l.date || l.startDate;
      // An unpaid day has zero payable attendance value. Any punches or
      // overtime requests on that same day remain only as an audit trail.
      if (overtimeDate && unpaidLeaveDates.has(overtimeDate)) return false;
      if (l.date) return l.date >= cycle.start && l.date <= cycle.end;
      if (l.startDate && l.endDate) return l.startDate <= cycle.end && l.endDate >= cycle.start;
      return false;
    });
    let rawNormalOvertimeMins = 0;
    let rawWeekendOvertimeMins = 0;
    const overtimeMinutesByMultiplier = new Map();
    let overtimeRequestsCount = 0;
    
    overtimeReqs.forEach(req => {
      overtimeRequestsCount++;
      if (req.startTime && req.endTime) {
        const [sh, sm] = req.startTime.split(':').map(Number);
        const [eh, em] = req.endTime.split(':').map(Number);
        let mins = Number(req?.rateDetails?.extraMins);
        if (!Number.isFinite(mins)) {
          mins = (eh * 60 + em) - (sh * 60 + sm);
          if (mins < 0) mins += 24 * 60;
        }
        
        if (hrSettings.maxDailyOvertimeHours) {
           const maxMins = hrSettings.maxDailyOvertimeHours * 60;
           if (mins > maxMins) mins = maxMins;
        }
        
        const reqDateStr = req.date || req.startDate;
        let isWeekendOrHoliday = false;
        
        if (reqDateStr) {
          const d = new Date(reqDateStr);
          const dayName = arabicDays[d.getDay()];
          const isWeekend = weekends.includes(dayName);
          const isHoliday = isDateInHoliday(reqDateStr);
          if (isWeekend || isHoliday) {
            isWeekendOrHoliday = true;
          }
        }
        
        const fallbackMultiplier = isWeekendOrHoliday
          ? (hrSettings.overtimeWeekendMultiplier || 1.50)
          : (hrSettings.overtimeMultiplier || 1.25);
        const storedRate = req.rate || req?.rateDetails?.baseRate;
        const rateParts = storedRate ? String(storedRate).split(':') : [];
        const explicitMultiplier = rateParts.length === 2 ? Number(rateParts[1]) : Number(storedRate);
        const requestMultiplier = Number.isFinite(explicitMultiplier) && explicitMultiplier > 0
          ? explicitMultiplier
          : fallbackMultiplier;
        overtimeMinutesByMultiplier.set(
          requestMultiplier,
          (overtimeMinutesByMultiplier.get(requestMultiplier) || 0) + mins
        );

        if (isWeekendOrHoliday) {
          rawWeekendOvertimeMins += mins;
        } else {
          rawNormalOvertimeMins += mins;
        }
      }
    });
    
    const roundedNormalOvertimeMins = roundMinutes(rawNormalOvertimeMins, hrSettings.timeRounding);
    const roundedWeekendOvertimeMins = roundMinutes(rawWeekendOvertimeMins, hrSettings.timeRounding);
    const totalNormalOvertimeHours = roundedNormalOvertimeMins / 60;
    const totalWeekendOvertimeHours = roundedWeekendOvertimeMins / 60;
    const totalOvertimeHours = totalNormalOvertimeHours + totalWeekendOvertimeHours;

    // Additions (Overtime)
    let overtimePay = 0;
    if (hrSettings.overtimeCalculationMethod === 'fixed_amount') {
       overtimePay = overtimeRequestsCount * (hrSettings.overtimeFixedAmount || 10);
    } else {
       overtimePay = [...overtimeMinutesByMultiplier.entries()].reduce((sum, [multiplier, minutes]) => {
         const roundedMinutes = roundMinutes(minutes, hrSettings.timeRounding);
         return sum + ((roundedMinutes / 60) * hourlyRate * multiplier);
       }, 0);
    }

    // Holiday Compensation
    let holidayPay = 0;
    let holidayAlternativeDays = 0;
    
    empAttendance.forEach(att => {
      if (att.date) {
        const hol = isDateInHoliday(att.date);
        if (hol) {
          const holSettings = hol.useDefaultSettings === false ? hol.customSettings : (hrSettings.holidayDefaults || { attendanceCompensation: 'alternative_day_and_overtime' });
          const comp = holSettings?.attendanceCompensation || 'none';
          
          if (comp.includes('alternative_day')) {
            holidayAlternativeDays += 1;
          }
          if (comp.includes('overtime_1_5')) {
            holidayPay += dailyRate * 1.5;
          } else if (comp.includes('overtime_1_25')) {
            holidayPay += dailyRate * 1.25;
          } else if (comp === 'overtime') {
            // Legacy fallback
            holidayPay += dailyRate * (hrSettings.overtimeWeekendMultiplier || 1.5);
          } else if (comp === 'alternative_day_and_overtime') {
            // Legacy fallback
            holidayPay += dailyRate * (hrSettings.overtimeWeekendMultiplier || 1.5);
          }
        }
      }
    });

    // Social Security Calculation
    let socialSecurityEmployeeDeduction = 0;
    let socialSecurityCompanyContribution = 0;
    
    if (emp.hasSocialSecurity) {
      const ssSalary = Number(emp.socialSecuritySalary) || basic;
      const employeePercentage = hrSettings.socialSecurityEmployeePercentage ?? 7.5;
      let companyPercentage = hrSettings.socialSecurityCompanyPercentage ?? 14.25;
      
      if (emp.isHazardousProfession) {
        companyPercentage += hrSettings.socialSecurityHazardousPercentage ?? 1;
      }
      
      socialSecurityEmployeeDeduction = ssSalary * (employeePercentage / 100);
      socialSecurityCompanyContribution = ssSalary * (companyPercentage / 100);
    }

    let advanceDeduction = 0;
    let advanceAddition = 0;

    const empAdvancesList = advances ? advances.filter(a => {
      const isEmpMatch = String(a.employeeId || '').trim() === String(emp.id || '').trim() || String(a.employeeName || '').trim() === String(emp.name || '').trim();
      if (!isEmpMatch || a.status !== 'موافق') return false;
      
      if (a.isInstallment && a.installments && a.installments.length > 0) {
        return a.installments.some(inst => inst.month === selectedMonth);
      }
      
      if (a.processedInPeriod && a.processedInPeriod !== selectedMonth) return false;
      if (!a.processedInPeriod) return ((a.date || a.createdAt) >= cycle.start && (a.date || a.createdAt) <= cycle.end);
      return true;
    }) : [];

    empAdvancesList.forEach(a => {
      let amountToProcess = 0;
      if (a.isInstallment && a.installments && a.installments.length > 0) {
        const dueInst = a.installments.find(inst => inst.month === selectedMonth);
        if (dueInst) amountToProcess = Number(dueInst.amount) || 0;
      } else {
        amountToProcess = Number(a.approvedAmount) || Number(a.amount) || 0;
      }

      if (a.type === 'سلفة شخصية') {
        advanceDeduction += amountToProcess;
      } else if (a.type === 'سلفة عمل' && a.paymentMethod === 'تصرف على الراتب القادم') {
        advanceAddition += amountToProcess;
      }
    });
    
    const totalDeductions = manualDeductions + lateDeduction + unpaidLeaveDeduction + unexcusedAbsenceDeduction + socialSecurityEmployeeDeduction + advanceDeduction;

    const transportAllowanceFull = Number(emp.transportationAllowance) || 0;
    const transportDailyRate = transportAllowanceFull / daysInMonth;
    const transportAllowanceAddition = Math.max(0, transportAllowanceFull - (unpaidLeaveDays * transportDailyRate));

    const totalBonusAmount = bonusAddition;
    const netSalary = basic + transportAllowanceAddition + overtimePay + holidayPay + advanceAddition + totalBonusAmount - totalDeductions;
    const actualAttendedDays = Math.max(0, elapsedWorkDays - unpaidLeaveDays - unexcusedAbsenceDays);
    const actualWorkHours = Math.max(0, actualAttendedDays * empStandardWorkHours - ((roundedLateMinutes + roundedMissionMinutes) / 60));

    return {
      ...emp,
      basic,
      transportAllowanceAddition: transportAllowanceAddition || 0,
      actualWorkHours: actualWorkHours || 0,
      empStandardWorkHours,
      workDays,
      totalOvertimeHours: totalOvertimeHours || 0,
      overtimePay: overtimePay || 0,
      holidayPay: holidayPay || 0,
      holidayAlternativeDays,
      lateDeduction: lateDeduction || 0,
      coveredLateMinutes: coveredLateMinutes || 0,
      unpaidLeaveDeduction: unpaidLeaveDeduction || 0,
      unexcusedAbsenceDays,
      unexcusedAbsenceDeduction: unexcusedAbsenceDeduction || 0,
      manualDeductions: manualDeductions || 0,
      advanceDeduction: advanceDeduction || 0,
      advanceAddition: advanceAddition || 0,
      bonusAddition: totalBonusAmount || 0,
      totalBonusAmount: totalBonusAmount || 0,
      bonusesList,
      socialSecurityEmployeeDeduction: socialSecurityEmployeeDeduction || 0,
      socialSecurityCompanyContribution: socialSecurityCompanyContribution || 0,
      totalDeductions: totalDeductions || 0,
      netSalary: netSalary || 0,
      violationsList: empViolations
    };
  });
};
